2021-03-20 17:38:23.623 - INFO - 4512 - azureml.train.automl.automlconfig._start_execution:206 - Submitting remote.
2021-03-20 18:17:32.692 - INFO - 4512 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-03-20 18:17:32.767 - INFO - 4512 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-03-20 18:17:32.806 - INFO - 4512 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-03-20 18:17:32.962 - INFO - 4512 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=156.28[ms]
2021-03-20 18:17:33.029 - INFO - 4512 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=262.31[ms]
2021-03-20 18:17:33.037 - INFO - 4512 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2021-03-20 18:17:58.334 - INFO - 4512 - azureml.automl.runtime.distributed.utilities.horovod_initialized:58 - Horovod not found in current environment. Distribution via Horovod will be disabled.
2021-03-20 18:18:02.810 - INFO - 4512 - azureml.automl.runtime.featurization.data_transformer.__init__:174 - Feature sweeping enabled: False
2021-03-20 18:18:02.827 - INFO - 4512 - azureml.automl.runtime.featurization.data_transformer.__init__:175 - Feature sweeping timeout: 86400
2021-03-20 18:18:07.816 - CRITICAL - 4512 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: XGBoostError
Message: [18:18:07] /mnt/xgboost/src/learner.cc:922: Check failed: header == serialisation_header_: 

  If you are loading a serialized model (like pickle in Python) generated by older
  XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version.  There's a simple script for helping
  the process. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for reference to the script, and more details about differences between saving model and
  serializing.


Stack trace:
  [bt] (0) /anaconda/envs/azureml_py36/lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x7c) [0x7f2db42f964c]
  [bt] (1) /anaconda/envs/azureml_py36/lib/libxgboost.so(xgboost::LearnerIO::Load(dmlc::Stream*)+0x66b) [0x7f2db4403f0b]
  [bt] (2) /anaconda/envs/azureml_py36/lib/libxgboost.so(XGBoosterUnserializeFromBuffer+0x5e) [0x7f2db42ed7fe]
  [bt] (3) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x69dd) [0x7f2ea93a09dd]
  [bt] (4) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x6067) [0x7f2ea93a0067]
  [bt] (5) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7f2ea93b8ede]
  [bt] (6) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7f2ea93b9915]
  [bt] (7) /anaconda/envs/azureml_py36/bin/python(_PyObject_FastCallDict+0x8b) [0x564c0a0dce3b]
  [bt] (8) /anaconda/envs/azureml_py36/bin/python(+0x199c0e) [0x564c0a164c0e]


Traceback:
  File "_model_download_utilities.py", line 177, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "core.py", line 189, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))

ExceptionTarget: Unspecified
2021-03-20 18:18:07.861 - CRITICAL - 4512 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: IncompatibleOrMissingDependency
Class: ConfigException
Message: ConfigException:
	Message: The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.
	InnerException: XGBoostError: [18:18:07] /mnt/xgboost/src/learner.cc:922: Check failed: header == serialisation_header_: 

  If you are loading a serialized model (like pickle in Python) generated by older
  XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version.  There's a simple script for helping
  the process. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for reference to the script, and more details about differences between saving model and
  serializing.


Stack trace:
  [bt] (0) /anaconda/envs/azureml_py36/lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x7c) [0x7f2db42f964c]
  [bt] (1) /anaconda/envs/azureml_py36/lib/libxgboost.so(xgboost::LearnerIO::Load(dmlc::Stream*)+0x66b) [0x7f2db4403f0b]
  [bt] (2) /anaconda/envs/azureml_py36/lib/libxgboost.so(XGBoosterUnserializeFromBuffer+0x5e) [0x7f2db42ed7fe]
  [bt] (3) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x69dd) [0x7f2ea93a09dd]
  [bt] (4) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x6067) [0x7f2ea93a0067]
  [bt] (5) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7f2ea93b8ede]
  [bt] (6) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7f2ea93b9915]
  [bt] (7) /anaconda/envs/azureml_py36/bin/python(_PyObject_FastCallDict+0x8b) [0x564c0a0dce3b]
  [bt] (8) /anaconda/envs/azureml_py36/bin/python(+0x199c0e) [0x564c0a164c0e]


	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.",
        "target": "get_output",
        "inner_error": {
            "code": "NotSupported",
            "inner_error": {
                "code": "IncompatibleOrMissingDependency"
            }
        },
        "reference_code": "910310e6-2433-40cd-b597-9ec2950bc1d8"
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 91, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 281, in _load_automl_model
    ) from e

ExceptionTarget: get_output
2021-03-20 18:18:07.900 - INFO - 4512 - azureml.train.automl._model_download_utilities._log_activity:93 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=34862.83[ms]
2021-03-20 18:18:07.901 - CRITICAL - 4512 - azureml.train.automl.run.log_traceback:224 - Type: IncompatibleOrMissingDependency
Class: ConfigException
Message: ConfigException:
	Message: The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.
	InnerException: XGBoostError: [18:18:07] /mnt/xgboost/src/learner.cc:922: Check failed: header == serialisation_header_: 

  If you are loading a serialized model (like pickle in Python) generated by older
  XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version.  There's a simple script for helping
  the process. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for reference to the script, and more details about differences between saving model and
  serializing.


Stack trace:
  [bt] (0) /anaconda/envs/azureml_py36/lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x7c) [0x7f2db42f964c]
  [bt] (1) /anaconda/envs/azureml_py36/lib/libxgboost.so(xgboost::LearnerIO::Load(dmlc::Stream*)+0x66b) [0x7f2db4403f0b]
  [bt] (2) /anaconda/envs/azureml_py36/lib/libxgboost.so(XGBoosterUnserializeFromBuffer+0x5e) [0x7f2db42ed7fe]
  [bt] (3) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x69dd) [0x7f2ea93a09dd]
  [bt] (4) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x6067) [0x7f2ea93a0067]
  [bt] (5) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7f2ea93b8ede]
  [bt] (6) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7f2ea93b9915]
  [bt] (7) /anaconda/envs/azureml_py36/bin/python(_PyObject_FastCallDict+0x8b) [0x564c0a0dce3b]
  [bt] (8) /anaconda/envs/azureml_py36/bin/python(+0x199c0e) [0x564c0a164c0e]


	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.",
        "target": "get_output",
        "inner_error": {
            "code": "NotSupported",
            "inner_error": {
                "code": "IncompatibleOrMissingDependency"
            }
        },
        "reference_code": "910310e6-2433-40cd-b597-9ec2950bc1d8"
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 704, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 91, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 281, in _load_automl_model
    ) from e

ExceptionTarget: get_output
2021-03-20 18:18:07.901 - INFO - 4512 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=35208.84[ms]
2021-03-20 18:21:25.239 - INFO - 4512 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-03-20 18:21:25.245 - INFO - 4512 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-03-20 18:21:25.264 - INFO - 4512 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-03-20 18:21:25.494 - INFO - 4512 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=229.45[ms]
2021-03-20 18:21:25.638 - INFO - 4512 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=393.67[ms]
2021-03-20 18:21:25.639 - INFO - 4512 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2021-03-20 18:21:26.777 - INFO - 4512 - azureml.automl.runtime.featurization.data_transformer.__init__:174 - Feature sweeping enabled: False
2021-03-20 18:21:26.777 - INFO - 4512 - azureml.automl.runtime.featurization.data_transformer.__init__:175 - Feature sweeping timeout: 86400
2021-03-20 18:21:26.782 - CRITICAL - 4512 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: XGBoostError
Message: [18:21:26] /mnt/xgboost/src/learner.cc:922: Check failed: header == serialisation_header_: 

  If you are loading a serialized model (like pickle in Python) generated by older
  XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version.  There's a simple script for helping
  the process. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for reference to the script, and more details about differences between saving model and
  serializing.


Stack trace:
  [bt] (0) /anaconda/envs/azureml_py36/lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x7c) [0x7f2db42f964c]
  [bt] (1) /anaconda/envs/azureml_py36/lib/libxgboost.so(xgboost::LearnerIO::Load(dmlc::Stream*)+0x66b) [0x7f2db4403f0b]
  [bt] (2) /anaconda/envs/azureml_py36/lib/libxgboost.so(XGBoosterUnserializeFromBuffer+0x5e) [0x7f2db42ed7fe]
  [bt] (3) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x69dd) [0x7f2ea93a09dd]
  [bt] (4) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x6067) [0x7f2ea93a0067]
  [bt] (5) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7f2ea93b8ede]
  [bt] (6) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7f2ea93b9915]
  [bt] (7) /anaconda/envs/azureml_py36/bin/python(_PyObject_FastCallDict+0x8b) [0x564c0a0dce3b]
  [bt] (8) /anaconda/envs/azureml_py36/bin/python(+0x199c0e) [0x564c0a164c0e]


Traceback:
  File "_model_download_utilities.py", line 177, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "core.py", line 189, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))

ExceptionTarget: Unspecified
2021-03-20 18:21:26.811 - CRITICAL - 4512 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: IncompatibleOrMissingDependency
Class: ConfigException
Message: ConfigException:
	Message: The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.
	InnerException: XGBoostError: [18:21:26] /mnt/xgboost/src/learner.cc:922: Check failed: header == serialisation_header_: 

  If you are loading a serialized model (like pickle in Python) generated by older
  XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version.  There's a simple script for helping
  the process. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for reference to the script, and more details about differences between saving model and
  serializing.


Stack trace:
  [bt] (0) /anaconda/envs/azureml_py36/lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x7c) [0x7f2db42f964c]
  [bt] (1) /anaconda/envs/azureml_py36/lib/libxgboost.so(xgboost::LearnerIO::Load(dmlc::Stream*)+0x66b) [0x7f2db4403f0b]
  [bt] (2) /anaconda/envs/azureml_py36/lib/libxgboost.so(XGBoosterUnserializeFromBuffer+0x5e) [0x7f2db42ed7fe]
  [bt] (3) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x69dd) [0x7f2ea93a09dd]
  [bt] (4) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x6067) [0x7f2ea93a0067]
  [bt] (5) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7f2ea93b8ede]
  [bt] (6) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7f2ea93b9915]
  [bt] (7) /anaconda/envs/azureml_py36/bin/python(_PyObject_FastCallDict+0x8b) [0x564c0a0dce3b]
  [bt] (8) /anaconda/envs/azureml_py36/bin/python(+0x199c0e) [0x564c0a164c0e]


	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.",
        "target": "get_output",
        "inner_error": {
            "code": "NotSupported",
            "inner_error": {
                "code": "IncompatibleOrMissingDependency"
            }
        },
        "reference_code": "910310e6-2433-40cd-b597-9ec2950bc1d8"
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 91, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 281, in _load_automl_model
    ) from e

ExceptionTarget: get_output
2021-03-20 18:21:26.811 - INFO - 4512 - azureml.train.automl._model_download_utilities._log_activity:93 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=1172.51[ms]
2021-03-20 18:21:26.813 - CRITICAL - 4512 - azureml.train.automl.run.log_traceback:224 - Type: IncompatibleOrMissingDependency
Class: ConfigException
Message: ConfigException:
	Message: The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.
	InnerException: XGBoostError: [18:21:26] /mnt/xgboost/src/learner.cc:922: Check failed: header == serialisation_header_: 

  If you are loading a serialized model (like pickle in Python) generated by older
  XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version.  There's a simple script for helping
  the process. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for reference to the script, and more details about differences between saving model and
  serializing.


Stack trace:
  [bt] (0) /anaconda/envs/azureml_py36/lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x7c) [0x7f2db42f964c]
  [bt] (1) /anaconda/envs/azureml_py36/lib/libxgboost.so(xgboost::LearnerIO::Load(dmlc::Stream*)+0x66b) [0x7f2db4403f0b]
  [bt] (2) /anaconda/envs/azureml_py36/lib/libxgboost.so(XGBoosterUnserializeFromBuffer+0x5e) [0x7f2db42ed7fe]
  [bt] (3) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x69dd) [0x7f2ea93a09dd]
  [bt] (4) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x6067) [0x7f2ea93a0067]
  [bt] (5) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7f2ea93b8ede]
  [bt] (6) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7f2ea93b9915]
  [bt] (7) /anaconda/envs/azureml_py36/bin/python(_PyObject_FastCallDict+0x8b) [0x564c0a0dce3b]
  [bt] (8) /anaconda/envs/azureml_py36/bin/python(+0x199c0e) [0x564c0a164c0e]


	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.",
        "target": "get_output",
        "inner_error": {
            "code": "NotSupported",
            "inner_error": {
                "code": "IncompatibleOrMissingDependency"
            }
        },
        "reference_code": "910310e6-2433-40cd-b597-9ec2950bc1d8"
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 704, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 91, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 281, in _load_automl_model
    ) from e

ExceptionTarget: get_output
2021-03-20 18:21:26.814 - INFO - 4512 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=1574.97[ms]
2021-03-20 18:36:56.479 - INFO - 4512 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-03-20 18:36:56.495 - INFO - 4512 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-03-20 18:36:56.500 - INFO - 4512 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-03-20 18:36:56.644 - INFO - 4512 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=143.59[ms]
2021-03-20 18:36:56.698 - INFO - 4512 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=202.37[ms]
2021-03-20 18:36:56.698 - INFO - 4512 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2021-03-20 18:36:57.527 - INFO - 4512 - azureml.automl.runtime.featurization.data_transformer.__init__:174 - Feature sweeping enabled: False
2021-03-20 18:36:57.528 - INFO - 4512 - azureml.automl.runtime.featurization.data_transformer.__init__:175 - Feature sweeping timeout: 86400
2021-03-20 18:36:57.535 - CRITICAL - 4512 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: XGBoostError
Message: [18:36:57] /mnt/xgboost/src/learner.cc:922: Check failed: header == serialisation_header_: 

  If you are loading a serialized model (like pickle in Python) generated by older
  XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version.  There's a simple script for helping
  the process. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for reference to the script, and more details about differences between saving model and
  serializing.


Stack trace:
  [bt] (0) /anaconda/envs/azureml_py36/lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x7c) [0x7f2db42f964c]
  [bt] (1) /anaconda/envs/azureml_py36/lib/libxgboost.so(xgboost::LearnerIO::Load(dmlc::Stream*)+0x66b) [0x7f2db4403f0b]
  [bt] (2) /anaconda/envs/azureml_py36/lib/libxgboost.so(XGBoosterUnserializeFromBuffer+0x5e) [0x7f2db42ed7fe]
  [bt] (3) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x69dd) [0x7f2ea93a09dd]
  [bt] (4) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x6067) [0x7f2ea93a0067]
  [bt] (5) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7f2ea93b8ede]
  [bt] (6) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7f2ea93b9915]
  [bt] (7) /anaconda/envs/azureml_py36/bin/python(_PyObject_FastCallDict+0x8b) [0x564c0a0dce3b]
  [bt] (8) /anaconda/envs/azureml_py36/bin/python(+0x199c0e) [0x564c0a164c0e]


Traceback:
  File "_model_download_utilities.py", line 177, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
  File "core.py", line 189, in _check_call
    if not isinstance(cptr, ctypes.POINTER(ctype)):

ExceptionTarget: Unspecified
2021-03-20 18:36:57.579 - CRITICAL - 4512 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: IncompatibleOrMissingDependency
Class: ConfigException
Message: ConfigException:
	Message: The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.
	InnerException: XGBoostError: [18:36:57] /mnt/xgboost/src/learner.cc:922: Check failed: header == serialisation_header_: 

  If you are loading a serialized model (like pickle in Python) generated by older
  XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version.  There's a simple script for helping
  the process. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for reference to the script, and more details about differences between saving model and
  serializing.


Stack trace:
  [bt] (0) /anaconda/envs/azureml_py36/lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x7c) [0x7f2db42f964c]
  [bt] (1) /anaconda/envs/azureml_py36/lib/libxgboost.so(xgboost::LearnerIO::Load(dmlc::Stream*)+0x66b) [0x7f2db4403f0b]
  [bt] (2) /anaconda/envs/azureml_py36/lib/libxgboost.so(XGBoosterUnserializeFromBuffer+0x5e) [0x7f2db42ed7fe]
  [bt] (3) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x69dd) [0x7f2ea93a09dd]
  [bt] (4) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x6067) [0x7f2ea93a0067]
  [bt] (5) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7f2ea93b8ede]
  [bt] (6) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7f2ea93b9915]
  [bt] (7) /anaconda/envs/azureml_py36/bin/python(_PyObject_FastCallDict+0x8b) [0x564c0a0dce3b]
  [bt] (8) /anaconda/envs/azureml_py36/bin/python(+0x199c0e) [0x564c0a164c0e]


	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.",
        "target": "get_output",
        "inner_error": {
            "code": "NotSupported",
            "inner_error": {
                "code": "IncompatibleOrMissingDependency"
            }
        },
        "reference_code": "910310e6-2433-40cd-b597-9ec2950bc1d8"
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 91, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 281, in _load_automl_model
    ) from e

ExceptionTarget: get_output
2021-03-20 18:36:57.579 - INFO - 4512 - azureml.train.automl._model_download_utilities._log_activity:93 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=880.9[ms]
2021-03-20 18:36:57.580 - CRITICAL - 4512 - azureml.train.automl.run.log_traceback:224 - Type: IncompatibleOrMissingDependency
Class: ConfigException
Message: ConfigException:
	Message: The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.
	InnerException: XGBoostError: [18:36:57] /mnt/xgboost/src/learner.cc:922: Check failed: header == serialisation_header_: 

  If you are loading a serialized model (like pickle in Python) generated by older
  XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version.  There's a simple script for helping
  the process. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for reference to the script, and more details about differences between saving model and
  serializing.


Stack trace:
  [bt] (0) /anaconda/envs/azureml_py36/lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x7c) [0x7f2db42f964c]
  [bt] (1) /anaconda/envs/azureml_py36/lib/libxgboost.so(xgboost::LearnerIO::Load(dmlc::Stream*)+0x66b) [0x7f2db4403f0b]
  [bt] (2) /anaconda/envs/azureml_py36/lib/libxgboost.so(XGBoosterUnserializeFromBuffer+0x5e) [0x7f2db42ed7fe]
  [bt] (3) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x69dd) [0x7f2ea93a09dd]
  [bt] (4) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x6067) [0x7f2ea93a0067]
  [bt] (5) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7f2ea93b8ede]
  [bt] (6) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7f2ea93b9915]
  [bt] (7) /anaconda/envs/azureml_py36/bin/python(_PyObject_FastCallDict+0x8b) [0x564c0a0dce3b]
  [bt] (8) /anaconda/envs/azureml_py36/bin/python(+0x199c0e) [0x564c0a164c0e]


	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.",
        "target": "get_output",
        "inner_error": {
            "code": "NotSupported",
            "inner_error": {
                "code": "IncompatibleOrMissingDependency"
            }
        },
        "reference_code": "910310e6-2433-40cd-b597-9ec2950bc1d8"
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 704, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 91, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 281, in _load_automl_model
    ) from e

ExceptionTarget: get_output
2021-03-20 18:36:57.580 - INFO - 4512 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=1101.25[ms]
2021-03-20 18:41:02.239 - INFO - 20738 - azureml.train.automl.automlconfig._start_execution:206 - Submitting remote.
2021-03-20 19:34:04.332 - INFO - 20738 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-03-20 19:34:04.424 - INFO - 20738 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-03-20 19:34:04.444 - INFO - 20738 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-03-20 19:34:04.595 - INFO - 20738 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=150.91[ms]
2021-03-20 19:34:04.679 - INFO - 20738 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=254.87[ms]
2021-03-20 19:34:04.693 - INFO - 20738 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2021-03-20 19:34:06.806 - INFO - 20738 - azureml.automl.runtime.distributed.utilities.horovod_initialized:58 - Horovod not found in current environment. Distribution via Horovod will be disabled.
2021-03-20 19:34:07.705 - INFO - 20738 - azureml.automl.runtime.featurization.data_transformer.__init__:174 - Feature sweeping enabled: False
2021-03-20 19:34:07.712 - INFO - 20738 - azureml.automl.runtime.featurization.data_transformer.__init__:175 - Feature sweeping timeout: 86400
2021-03-20 19:34:09.088 - INFO - 20738 - azureml.train.automl._model_download_utilities._log_activity:93 - ActivityCompleted: Activity=DownloadModel, HowEnded=Success, Duration=4393.99[ms]
2021-03-20 19:34:09.130 - INFO - 20738 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=4798.06[ms]
2021-03-20 19:50:24.908 - INFO - 20738 - azureml.train.automl.run._log_activity:55 - ActivityStarted: RegisterModel
2021-03-20 19:50:24.972 - INFO - 20738 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-03-20 19:50:25.110 - INFO - 20738 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=138.7[ms]
2021-03-20 19:50:26.056 - INFO - 20738 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=RegisterModel, HowEnded=Success, Duration=1147.79[ms]
